apiVersion: v1
kind: Service
metadata:
  name: {{ include "mern-backend.fullname" . }}
  labels:
    {{- include "mern-backend.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace}}    
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "mern-backend.selectorLabels" . | nindent 4 }}
